### PR TITLE
teamspage/feature sameer

### PR DESCRIPTION
**Pull request by Sameer01-01**
completed the teams page 
(the small logo in the bottom left corner is because i was using an page screenshot extension and its not there in the website)

### Desktop layout

desktop view

### Mobile layout

mobile view

### ipad layout

ipad view

### CODE REVIEW

**Comment by ashibad** [comment]
Fantastic work on this! , I don’t see any issues here—great job!

**Comment by ashibad** [comment]
Just one more thing, could you please integrate the navbar component from the global directory into this page?

**Comment by Sameer01-01** [comment]
> Just one more thing, could you please integrate the navbar component from the global directory into this page?

Sure..I'll do the changes

**Comment by Sameer01-01** [comment]
> Fantastic work on this! , I don’t see any issues here—great job!

Thanks a lot!!

**Pull request merged**
